name: PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "app/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.x"

      - name: Install locked dependencies
        run: bun install --frozen-lockfile

      - name: Lint files
        run: bun run lint
        env:
          CI: true

      - name: Lint files
        run: bun run format
        env:
          CI: true

      - name: Lint files
        run: bun run type-check
        env:
          CI: true
